"""Class and tools to read Visualization Toolkit (VTK_) data.

.. _VTK: https://vtk.org/
"""

# standard library packages
from os.path import join
from os import sep
from glob import glob
from typing import Callable, Union, List, Dict

# third party packages
import torch as pt
from vtk import vtkUnstructuredGridReader, vtkXMLUnstructuredGridReader
from vtk.numpy_interface.dataset_adapter import WrapDataObject, UnstructuredGrid

# flowtorch packages
from flowtorch import DEFAULT_DTYPE
from .dataloader import Dataloader
from .utils import check_and_standardize_path, check_list_or_str


class VTKDataloader(Dataloader):
    """Load unstructured VTK files and time series.

    The loader assumes that snapshots are stored in individual VTK files.
    Currently, only unstructured mesh data are supported.

    Examples

    >>> from flowtorch import DATASETS
    >>> from flowtorch.data import VTKDataloader
    >>> path = DATASETS["vtk_cylinder_re200_flexi"]
    >>> loader = VTKDataloader.from_flexi(path, "Cylinder_Re200_Solution_")
    >>> loader.write_times
    ["0000000", "0000005", "0000300"]
    >>> loader.field_names
    {'0000000': ['Density', 'MomentumX', 'MomentumY', 'MomentumZ']}
    >>> density = loader.load_snapshot("Density", loader.write_times)
    >>> density.shape
    torch.Size([729000, 3])

    >>> from flowtorch import DATASETS
    >>> from flowtorch.data import VTKDataloader
    >>> path = DATASETS["vtk_su2_airfoil_2D"]
    >>> loader = VTKDataloader.from_su2(path, "flow_")
    >>> p, U = loader.load_snapshot(["Pressure", "Velocity"], loader.write_times[0])
    >>> U.shape
    torch.Size([214403, 3])

    """

    def __init__(
        self,
        path: str,
        vtk_reader: Union[vtkUnstructuredGridReader, vtkXMLUnstructuredGridReader],
        prefix: str = "",
        suffix: str = "",
        dtype: str = DEFAULT_DTYPE,
    ):
        """Create a VTKDataloader instance from a folder of VTK files.

        The loader assumes that the write time is encoded in the file name.

        :param path: path to folder containing VTK files
        :type path: str
        :param vtk_reader: unstructured VTK reader for XML or legacy VTK format
        :type vtk_reader: Union[vtkUnstructuredGridReader, vtkXMLUnstructuredGridReader]
        :param prefix: part of file name before time value, defaults to ""
        :type prefix: str, optional
        :param suffix: part of file name after time value, defaults to ""
        :type suffix: str, optional
        :param dtype: tensor type, defaults to DEFAULT_DTYPE
        :type dtype: str, optional
        """
        self._path = path
        self._vtk_reader = vtk_reader
        self._prefix = prefix
        self._suffix = suffix
        self._dtype = dtype
        self._write_times: List[str] | None = None
        self._field_names: Dict[str, List[str]] | None = None

    @classmethod
    def from_flexi(
        cls,
        path: str,
        prefix: str = "",
        suffix: str = ".000000000.vtu",
        dtype: str = DEFAULT_DTYPE,
    ):
        """Create loader instance from VTK files generated by Flexi_.

        Flexi supports the output of field and surface data as unstructured
        XML-based VTK files.

        .. _Flexi: https://www.flexi-project.org/

        :param path: path to folder containing VTK files
        :type path: str
        :param prefix: part of file name before time value, defaults to ""
        :type prefix: str, optional
        :param suffix: part of file name after time value, defaults to ".000000000.vtu"
        :type suffix: str, optional
        :param dtype: tensor type, defaults to DEFAULT_DTYPE
        :type dtype: str, optional
        """
        return cls(path, vtkXMLUnstructuredGridReader, prefix, suffix, dtype)

    @classmethod
    def from_su2(
        cls,
        path: str,
        prefix: str = "",
        suffix: str = ".vtk",
        dtype: str = DEFAULT_DTYPE,
    ):
        """Create loader instance from VTK files generated by SU2_.

        .. _SU2: https://su2code.github.io/

        :param path: path to folder containing VTK files
        :type path: str
        :param prefix: part of file name before time value, defaults to ""
        :type prefix: str, optional
        :param suffix: part of file name after time value, defaults to ".vtk"
        :type suffix: str, optional
        :param dtype: tensor type, defaults to DEFAULT_DTYPE
        :type dtype: str, optional
        """
        return cls(path, vtkUnstructuredGridReader, prefix, suffix, dtype)

    def _create_vtk_reader(self, file_path: str) -> UnstructuredGrid:
        """Create a VTK reader object for unstructured grids.

        :param file_path: location of the VTK file
        :type file_path: str
        :return: VTK reader for unstructured grids
        :rtype: UnstructuredGrid
        """
        reader = self._vtk_reader()
        reader.SetFileName(file_path)
        if hasattr(reader, "ReadAllVectorsOn"):
            reader.ReadAllVectorsOn()
        if hasattr(reader, "ReadAllScalarsOn"):
            reader.ReadAllScalarsOn()
        reader.Update()
        return WrapDataObject(reader.GetOutput())

    def _build_file_path(self, time: str) -> str:
        """Create file path VTK file.

        :param time: snapshot write time
        :type time: str
        :return: VTK file location
        :rtype: str
        """
        return join(self._path, f"{self._prefix}{time}{self._suffix}")

    def load_snapshot(
        self, field_name: Union[List[str], str], time: Union[List[str], str]
    ) -> Union[List[pt.Tensor], pt.Tensor]:
        check_list_or_str(field_name, "field_name")
        check_list_or_str(time, "time")
        # load multiple fields
        if isinstance(field_name, list):
            if isinstance(time, list):
                return self._load_multiple_snapshots(field_name, time)
            else:
                snapshot = self._create_vtk_reader(
                    self._build_file_path(time)
                ).PointData
                return [
                    pt.tensor(snapshot[name], dtype=self._dtype) for name in field_name
                ]
        # load single field
        else:
            if isinstance(time, list):
                return self._load_multiple_snapshots([field_name], time)[0]
            else:
                return pt.tensor(
                    self._create_vtk_reader(self._build_file_path(time)).PointData[
                        field_name
                    ],
                    dtype=self._dtype,
                )

    def _load_multiple_snapshots(
        self, field_names: List[str], times: List[str]
    ) -> List[pt.Tensor]:
        """Load each VTK file once into preallocated time-last tensors."""
        if not times:
            raise ValueError("At least one snapshot time must be provided")
        snapshot = self._create_vtk_reader(self._build_file_path(times[0])).PointData
        first_fields = [
            pt.tensor(snapshot[field], dtype=self._dtype) for field in field_names
        ]
        field_shapes = [first.shape for first in first_fields]
        series = [first.new_empty((*first.shape, len(times))) for first in first_fields]
        for output, first in zip(series, first_fields):
            output[..., 0].copy_(first)
        del first_fields
        for index, time in enumerate(times[1:], start=1):
            snapshot = self._create_vtk_reader(self._build_file_path(time)).PointData
            for output, field, shape in zip(series, field_names, field_shapes):
                current = pt.tensor(snapshot[field], dtype=self._dtype)
                if current.shape != shape:
                    raise ValueError(
                        f"Field {field!r} has shape {tuple(current.shape)} at "
                        f"time {time!r}; expected {tuple(shape)}"
                    )
                output[..., index].copy_(current)
        return series

    @property
    def write_times(self) -> List[str]:
        if self._write_times is None:
            files = glob(self._build_file_path("*"))
            self._write_times = sorted(
                [
                    f.split(sep)[-1][len(self._prefix) : -len(self._suffix)]
                    for f in files
                ],
                key=float,
            )
        return self._write_times

    @property
    def field_names(self) -> Dict[str, List[str]]:
        if self._field_names is None:
            snapshot = self._create_vtk_reader(
                self._build_file_path(self.write_times[0])
            )
            self._field_names = {self.write_times[0]: list(snapshot.PointData.keys())}
        return self._field_names

    @property
    def vertices(self) -> pt.Tensor:
        snapshot = self._create_vtk_reader(self._build_file_path(self.write_times[0]))
        return pt.tensor(snapshot.Points, dtype=self._dtype)

    @property
    def weights(self) -> pt.Tensor:
        raise NotImplementedError("The weights property is not yet implemented.")
