[tox]
envlist = py310, py312, py314
isolated_build = false
skip_missing_interpreters = true

[testenv]
usedevelop = true
deps =
    pytest
commands =
    pytest {posargs:-m "not integration"}
passenv =
    FLOWTORCH_DATASETS
